
spring:
  profiles: local

  redis:
     host: 127.0.0.1
     port: 6379
     password: dkwmfrjdns1!

server:
  port: 8081

api:
  server:
     info: http://localhost:3000/test

file:
  server:
      info: http://

restemplate:
  connectionTimeOut: 3000
  readTimeOut: 300
  defaultMaxPerRoute: 20
  maxToal: 50

---
spring:
  profiles: dev

  redis:
    host: 127.0.0.1
    port: 6379
    password: dkwmfrjdns1!

server:
  port: 8081

api:
  server:
    info: http://localhost:8082

file:
  server:
    info: http://

log:
  path: /home

restemplate:
  connectionTimeOut: 3000
  readTimeOut: 300
  defaultMaxPerRoute: 20
  maxToal: 50
